# Site settings
title: Catch A Ride
email: singhrmn22@outlook.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://catcharide.github.io" # the base hostname & protocol for your site
twitter_username: rmnsingh22
github_username:  rmnguleria

# Build settings
markdown: kramdown
